variable "env" {}
variable "project_name" {}
variable "component" {}
variable "instance_type" {}
variable "vpc_id" {}
variable "bastion_cidrs" {}
variable "app_port" {}
variable "sg_cidr_block" {}
variable "instance_capacity" {}
variable "vpc_zone_identifier" {}
variable "parameters" {}
variable "kms_key_id" {}
variable "prometheus_cidrs" {}
